# Generated by Django 3.0.5 on 2021-06-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_index=True, through='api.GenreTitle', to='api.Genre', verbose_name='Жанр'),
        ),
    ]
