# Generated by Django 3.0.5 on 2021-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210614_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введи название', max_length=200, verbose_name='Name')),
                ('category', models.IntegerField(verbose_name='Категория')),
                ('year', models.SmallIntegerField(help_text='Год выхода', null=True, verbose_name='Year')),
            ],
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
