# Generated by Django 3.0.5 on 2021-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210615_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.IntegerField(null=True, verbose_name='Категория'),
        ),
    ]
