# Generated by Django 3.0.5 on 2021-06-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210614_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Название', 'verbose_name_plural': 'Названия'},
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='name',
        ),
    ]
