# Generated by Django 3.0.5 on 2021-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210623_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(through='api.GenreTitle', to='api.Genre'),
        ),
    ]
