# Generated by Django 3.0.5 on 2021-06-23 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210623_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=10, help_text='Введите от 1 до 10', validators=[django.core.validators.MinValueValidator(1, message='Поставьте оценка от 1 до 10.'), django.core.validators.MaxValueValidator(10, message='Поставьте оценка от 1 до 10.')], verbose_name='Оценка'),
        ),
    ]
